require 'config.options'
require 'config.keymap'
require 'config.autocmds'
require 'config.pack'
require 'config.diagnostics'
require 'config.health'

require 'plugins.init'
-- require 'plugins.colorscheme'
-- require 'plugins.mini'
-- require 'plugins.which-key'
-- require 'plugins.guess-indent'
-- require 'plugins.todo-comments'
-- require 'plugins.gitsigns'
-- require 'plugins.telescope'
-- require 'plugins.treesitter'
-- require 'plugins.neo-tree'
-- require 'plugins.lazydev'
-- require 'plugins.lsp'
-- require 'plugins.blink'
-- require 'plugins.autopairs'
-- require 'plugins.conform'
-- require 'plugins.lint'
-- require 'plugins.debug'
-- require 'plugins.markdown'
-- require 'plugins.tmux'
-- require 'plugins.java'
